# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'


- task: TerraformInstaller@5
  inputs:
    displayName: init
    provider: 'azurerm'
    command: 'init'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'mi-qaecdevops-0001'
    backendAzureRmResourceGroupName: 'learn_terraform'
    backendAzureRmStorageAccountName: 'aecterraform200225'
    backendAzureRmContainerName: 'tf-state'
    backendAzureRmKey: 'github.tfstate'

- task: TerraformInstaller@5
  inputs:
    displayName: Plan
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'mi-qaecdevops-0001'

- task: TerraformInstaller@5
  inputs:
    displayName: Apply
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'mi-qaecdevops-0001'
